const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "mongodb+srv://mohsin:mohsin@cluster0.iauaztt.mongodb.net/?retryWrites=true&w=majority"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "mongodb+srv://mohsin:mohsin@cluster0.iauaztt.mongodb.net/?retryWrites=true&w=majority"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/GlobalTechInfo/SUHAIL-XMD";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.ibb.co/TgwRyHR/Ephoto360-com-166de101e03cd7.jpg" || "https://i.ibb.co/bH1kbX0/a4c0b1af253197d4837ff6760d5b81c0.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "© GlobalTechInfo" 


global.devs = "" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "true" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "https://i.ibb.co/pXyNHj8/suhail.jpg" // "image" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923444844060,923xxxxxxxx";

global.api_smd = "https://api.kyuurzy.site/api/download/aio" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_12_22_10_03_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODAsXG4gICAgICAgIDkwLFxuICAgICAgICAyMTksXG4gICAgICAgIDk1LFxuICAgICAgICAxNDcsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMjcsXG4gICAgICAgIDc5LFxuICAgICAgICA5OSxcbiAgICAgICAgMTEwLFxuICAgICAgICAxOTcsXG4gICAgICAgIDM3LFxuICAgICAgICA2MCxcbiAgICAgICAgOTksXG4gICAgICAgIDE0OCxcbiAgICAgICAgMjEwLFxuICAgICAgICAyMTgsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTg4LFxuICAgICAgICA3LFxuICAgICAgICA5NSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxNDQsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTY1LFxuICAgICAgICAzMyxcbiAgICAgICAgMTg3LFxuICAgICAgICA4MixcbiAgICAgICAgMjM4LFxuICAgICAgICAyNDYsXG4gICAgICAgIDEwMyxcbiAgICAgICAgNjhcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTcsXG4gICAgICAgIDE2MixcbiAgICAgICAgNjUsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMCxcbiAgICAgICAgMTIxLFxuICAgICAgICAyMTYsXG4gICAgICAgIDE1LFxuICAgICAgICAxNTksXG4gICAgICAgIDE3MixcbiAgICAgICAgNDYsXG4gICAgICAgIDMzLFxuICAgICAgICAyMjEsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxNTcsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjUsXG4gICAgICAgIDc5LFxuICAgICAgICAyMTgsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTEyLFxuICAgICAgICAxNzQsXG4gICAgICAgIDMwLFxuICAgICAgICAxMjcsXG4gICAgICAgIDY1LFxuICAgICAgICAyMyxcbiAgICAgICAgMjM0LFxuICAgICAgICAzLFxuICAgICAgICAyMTYsXG4gICAgICAgIDk1LFxuICAgICAgICAxNVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTMsXG4gICAgICAgIDg1LFxuICAgICAgICAxMDYsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTI3LFxuICAgICAgICAyMzIsXG4gICAgICAgIDE0LFxuICAgICAgICAxMTQsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjMxLFxuICAgICAgICAxOTksXG4gICAgICAgIDQsXG4gICAgICAgIDE2NyxcbiAgICAgICAgNzMsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTM5LFxuICAgICAgICAxMCxcbiAgICAgICAgMTgzLFxuICAgICAgICAxMDUsXG4gICAgICAgIDExLFxuICAgICAgICAxMDksXG4gICAgICAgIDQ2LFxuICAgICAgICA1MyxcbiAgICAgICAgMTgxLFxuICAgICAgICAyMDIsXG4gICAgICAgIDc0LFxuICAgICAgICAyMjksXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTE0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzNixcbiAgICAgICAgMTUzLFxuICAgICAgICAyMjYsXG4gICAgICAgIDc3LFxuICAgICAgICAyOSxcbiAgICAgICAgMjgsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjM3LFxuICAgICAgICAyMjcsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTQ1LFxuICAgICAgICA5NCxcbiAgICAgICAgMjM3LFxuICAgICAgICA5MCxcbiAgICAgICAgNjQsXG4gICAgICAgIDExMixcbiAgICAgICAgMTMwLFxuICAgICAgICAyMTUsXG4gICAgICAgIDE1MSxcbiAgICAgICAgOTEsXG4gICAgICAgIDE1NixcbiAgICAgICAgMzcsXG4gICAgICAgIDIwMCxcbiAgICAgICAgNSxcbiAgICAgICAgMTE2LFxuICAgICAgICAxNjYsXG4gICAgICAgIDU1LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxNTAsXG4gICAgICAgIDJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE3NixcbiAgICAgICAgMjA5LFxuICAgICAgICAxMzQsXG4gICAgICAgIDI0OSxcbiAgICAgICAgNzgsXG4gICAgICAgIDIyMCxcbiAgICAgICAgODcsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTQ4LFxuICAgICAgICA1MixcbiAgICAgICAgMjI5LFxuICAgICAgICAxOTAsXG4gICAgICAgIDIzNCxcbiAgICAgICAgNTIsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMTI5LFxuICAgICAgICAxMDEsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTExLFxuICAgICAgICAxNDgsXG4gICAgICAgIDQ1LFxuICAgICAgICAxODcsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTU5LFxuICAgICAgICAxNzcsXG4gICAgICAgIDE2MixcbiAgICAgICAgNzQsXG4gICAgICAgIDUsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTUwLFxuICAgICAgICAxMzgsXG4gICAgICAgIDczXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2OSxcbiAgICAgICAgMzUsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTUsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjM5LFxuICAgICAgICAxMjgsXG4gICAgICAgIDc1LFxuICAgICAgICAyOCxcbiAgICAgICAgMjI4LFxuICAgICAgICAyNTEsXG4gICAgICAgIDIxLFxuICAgICAgICAyNTIsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTE2LFxuICAgICAgICA0MyxcbiAgICAgICAgNTIsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMzksXG4gICAgICAgIDE4LFxuICAgICAgICAyNDAsXG4gICAgICAgIDIzLFxuICAgICAgICA5NSxcbiAgICAgICAgMjQsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMzQsXG4gICAgICAgIDcsXG4gICAgICAgIDI0MCxcbiAgICAgICAgNjIsXG4gICAgICAgIDYzLFxuICAgICAgICAyOCxcbiAgICAgICAgNTNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMzksXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMixcbiAgICAgICAgICAxMDRcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNixcbiAgICAgICAgICA0NCxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgMTY0LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICAxMDlcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMTQsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTYyLFxuICAgICAgICAyMDksXG4gICAgICAgIDYxLFxuICAgICAgICA1NixcbiAgICAgICAgMTY1LFxuICAgICAgICAyMDAsXG4gICAgICAgIDk1LFxuICAgICAgICAxMyxcbiAgICAgICAgMzEsXG4gICAgICAgIDg3LFxuICAgICAgICAyMixcbiAgICAgICAgMjI0LFxuICAgICAgICA1OSxcbiAgICAgICAgMjI5LFxuICAgICAgICAyNSxcbiAgICAgICAgMTYzLFxuICAgICAgICA2NixcbiAgICAgICAgMTAxLFxuICAgICAgICAyMSxcbiAgICAgICAgNzYsXG4gICAgICAgIDEyNixcbiAgICAgICAgMjI1LFxuICAgICAgICAyMzAsXG4gICAgICAgIDU2LFxuICAgICAgICAxNTMsXG4gICAgICAgIDUxLFxuICAgICAgICAyMDYsXG4gICAgICAgIDM0LFxuICAgICAgICA0MSxcbiAgICAgICAgMTI1LFxuICAgICAgICAyMzgsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjEyLFxuICAgICAgICAyNTMsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTg3LFxuICAgICAgICA0MyxcbiAgICAgICAgMjUyLFxuICAgICAgICA2OSxcbiAgICAgICAgMTE2LFxuICAgICAgICAzOCxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxOTEsXG4gICAgICAgIDM0LFxuICAgICAgICA5OCxcbiAgICAgICAgMSxcbiAgICAgICAgMTkwLFxuICAgICAgICAxNDUsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTgxLFxuICAgICAgICAyNTMsXG4gICAgICAgIDk1LFxuICAgICAgICAyLFxuICAgICAgICAyMDgsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTAyLFxuICAgICAgICAxOTcsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjA4LFxuICAgICAgICAzMCxcbiAgICAgICAgMTMwLFxuICAgICAgICAxMzVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDkxLFxuICBcImFkdlNlY3JldEtleVwiOiBcIk9LbERCUGFMb24rRHdYTWRoQmtQV0YyMUY1ZEtTaW9qYkczR1dnS3Z5Rm89XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0OTAyNTk2Nzk2NEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMTBCNjFGQzAyOTY0MDczMDA0MEE0MUI3RjBBQzQ0MTBcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI3OTU4MTMyXG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIjltQXlNSlZ5UVllME5KeXhZbDhnRmdcIixcbiAgXCJwaG9uZUlkXCI6IFwiYzBiM2NjMzktNDIwMC00ZWU0LTgxZDMtZDVkOWEyMWQ0YmFmXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEyOSxcbiAgICAgIDI0NSxcbiAgICAgIDI1MCxcbiAgICAgIDEyNCxcbiAgICAgIDEzNixcbiAgICAgIDE1NixcbiAgICAgIDYyLFxuICAgICAgMjMwLFxuICAgICAgMTE3LFxuICAgICAgMTUyLFxuICAgICAgMTM3LFxuICAgICAgMTM5LFxuICAgICAgMjM5LFxuICAgICAgNjQsXG4gICAgICAxMzIsXG4gICAgICAxODAsXG4gICAgICAxMTEsXG4gICAgICAyMjQsXG4gICAgICAxMTQsXG4gICAgICAyMDNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDExMSxcbiAgICAgIDIwNixcbiAgICAgIDE5OCxcbiAgICAgIDIxMCxcbiAgICAgIDE0NixcbiAgICAgIDk3LFxuICAgICAgMTM2LFxuICAgICAgNTcsXG4gICAgICA0LFxuICAgICAgMjM4LFxuICAgICAgMjU1LFxuICAgICAgMjUzLFxuICAgICAgMTg0LFxuICAgICAgOTUsXG4gICAgICAyMjMsXG4gICAgICAxMDIsXG4gICAgICAyMDEsXG4gICAgICAyNSxcbiAgICAgIDE4NyxcbiAgICAgIDQ4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTDdTbjg0Q0VPdVkrcmNHR0JBZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJDNzRYc1lGYnpkMzh2d01pdGxNVDE5Z01nNHh6T3hoTUVPQkVtM1pZaGlBPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIjBwQ0RaMUlYaWRrbFp2SU1wRTJyN3Nscm1UejRXaDRvamxOSEFoYkNQN2dFemtvZ0w5SDBVYzlmbDJ1RUdQZjBkVmQ4Zjc4WW0xVGFBajVIOFJCTENnPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIjF1QnBMNE1WWFA2UUVsUlc3QVNUVGRaZDloRFh4Q2NrVFBIQ041V3pjRGVBRnlXbGhnQW9ncGErVloyQWhHUEhvTHBGNnRGd1g0ck5WbGJNdzRlVmhnPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0OTAyNTk2Nzk2NDoxNUBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMjM1MzgxNjIyNjI4NTM0OjE1QGxpZFwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0OTAyNTk2Nzk2NDoxNUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjUyLFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAzMlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI3OTU4MTI3LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSlN1XCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKUzAuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJIYnhzNHhWaVhVd2lSaDlKMzQ0SERMWWZZSzNuRkExVXo3OEp1TkIxMFRnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwMDk2NzIzMCxcImN1cnJlbnRJbmRleFwiOjEyLFwiZGV2aWNlSW5kZXhlc1wiOlswLDExLDEyXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjU5NTgxNzIxNzhcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKUzEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIyVVZJbmhTbExkdUtYOGJHVHVKbnRyaEM4OW85VXNvMHRsamdVeTNlYlVRPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwMDk2NzIzMCxcImN1cnJlbnRJbmRleFwiOjEyLFwiZGV2aWNlSW5kZXhlc1wiOlswLDExXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKUzIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJZazNFTHlSU0hObTVHT2JUT0YyZ0Q4VklpM0dSSzloYkY2M2VjekdoZTVnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwMDk2NzIzMCxcImN1cnJlbnRJbmRleFwiOjE1LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEzLDE0LDE1XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKUzMuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJwWXpWLzN3SHZianVZazZxSzNnejFBenpkTW9JVVoxTGVHTW1nWGd3ZVBzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwMDk2NzIzMCxcImN1cnJlbnRJbmRleFwiOjE1LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEzLDE0XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKUzQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIwbkwvL0N1WFlRZnRUMC9UUnhDVU9xdWUraUE4QlAwc2NqUDZiUUlZSXpnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwMDk2NzIzMCxcImN1cnJlbnRJbmRleFwiOjE1LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEzXX0sXCJ0aW1lc3RhbXBcIjpcIjE3Mjc5NTgxMTA5OTVcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKU3QuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJXa2lvVytNdStPcURFOGxTbm43N012SXFZaTNCZ1ErTmcybE5XVC9WbnBzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwMDk2NzIyOSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE3NDg3Nzg2NTcxXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSlN1Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiWTNWYTZVa3M3ejRTeFlOZzNxcm1LSGRtL1FiMHY3a2ZjeUFFZDNwcG9TWT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo3MDA5NjcyMjksXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUpTdy5qc29uIjogIntcImtleURhdGFcIjpcIko5eVovM0FaTzh3Uk1TcTluM0V2Tk5tUmh2VzZpS0QzVC9rcVRwSzl1MlU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NzAwOTY3MjMwLFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjA2NDY5NDM2MzNcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKU3guanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJpM0hHSzkwaHZrRmJzZWxiWUU4clFoeE9qZkl1UkhNLy9mZWdRL0hwamo4PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwMDk2NzIzMCxcImN1cnJlbnRJbmRleFwiOjksXCJkZXZpY2VJbmRleGVzXCI6WzAsMSw5XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKU3kuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJuRTFTd0N1Yi82MlRRSTJqMlg5bEF1Z0RzT3RadThIUlJ2bi9zRjJyOTdFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwMDk2NzIzMCxcImN1cnJlbnRJbmRleFwiOjExLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMTAsMTFdfSxcInRpbWVzdGFtcFwiOlwiMTcyNDg1Nzk0Njc1M1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUpTei5qc29uIjogIntcImtleURhdGFcIjpcInF3Y1piK1pjRVFmbTJHRFhlRU43d0M5aTk1eGlBQ0tPd0NwY0hvSGtMWVE9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NzAwOTY3MjMwLFwiY3VycmVudEluZGV4XCI6MTIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMTAsMTEsMTJdfSxcInRpbWVzdGFtcFwiOlwiMTcyNTQ5NTY1NTY2MlwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.0.1-developement-x",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ GlobalTechInfo ® 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@GlobalTechInfo"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "Suhail-XMD",
  ownername:process.env.OWNER_NAME|| "Suhail-X",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "yepeTQaFk7r9ymusihgXYvdN",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "0cdb1aed858329b9793413672094ce0d";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
